name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install huggingface_hub

    - name: Deploy to Hugging Face
      run: |
        huggingface-cli login --token {{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}}
        git lfs install
        git add .
        git commit -m "Deploying to Hugging Face"
        git push origin main

